### ISSUE TITLE
EC2 인스턴스에 MySQL 설치하기

### ISSUE THREAD

**Issue by zoomKoding** [woowa-techcamp-2020/todo-7#10]
## 이슈 요약

> 해당 이슈가 어떤 이슈인지에 대한 간략한 설명을 추가합니다.

EC2 인스턴스에 MySQL을 설치합니다.

**Comment by younho9** [comment]
<img width="592" alt="스크린샷 2020-07-14 오후 7 13 19" src="https://user-images.githubusercontent.com/48426991/87414033-1608cb80-c606-11ea-9454-9a438f3ce5f1.png">

처음 해봤는데 같이 따라가보니 막힘없이 잘 했네요.
