### ISSUE TITLE
백엔드 API 설계하기

### ISSUE THREAD

**Issue by zoomKoding** [woowa-techcamp-2020/todo-7#12]
## 이슈 요약

> 해당 이슈가 어떤 이슈인지에 대한 간략한 설명을 추가합니다.

필요한 Frontend의 API를 정하고 요청과 응답의 형식을 정의합니다.

## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [ ] 각 유저 액션에 필요한 데이터 요청 정의하기
- [ ] API 구조 잡기
- [ ] API 요청과 응답 형식 정하기

**Comment by younho9** [comment]
# signIn

## Request

### Endpoint

`POST` `/login`

### Body

| Property   | Type     | Description   |
| ---------- | -------- | ------------- |
| `username` | `string` | 유저 아이디   |
| `password` | `string` | 유저 비밀번호 |

### Response

| Property  | Type      | Description           |
| --------- | --------- | --------------------- |
| `success` | `boolean` | 로그인 성공 또는 실패 |

# getProjects

## Request

### Endpoint

`GET` `/projects/[user.id]`

### Params

| Property  | Type     | Description   |
| --------- | -------- | ------------- |
| `user.id` | `number` | 유저 고유번호 |

### Response

| Property   | Type        | Description                          |
| ---------- | ----------- | ------------------------------------ |
| `projects` | `Project[]` | 유저가 참여하고 있는 프로젝트 리스트 |

# getUsers

## Request

### Endpoint

`GET` `/users/[project.id]`

### Params

| Property     | Type     | Description       |
| ------------ | -------- | ----------------- |
| `project.id` | `number` | 프로젝트 고유번호 |

### Response

| Property | Type     | Description                     |
| -------- | -------- | ------------------------------- |
| `users`  | `User[]` | 프로젝트에 참여하는 유저 리스트 |

# getProjectData

## Request

### Endpoint

`GET` `/project/[project.id]`

### Params

| Property     | Type     | Description       |
| ------------ | -------- | ----------------- |
| `project.id` | `number` | 프로젝트 고유번호 |

### Response

| Property  | Type      | Description                                         |
| --------- | --------- | --------------------------------------------------- |
| `project` | `Project` | 프로젝트에 포함된 그룹, 노트, 이벤트 등 모든 데이터 |

# createProject

## Request

### Endpoint

`POST` `/project`

### Body

| Property                 | Type     | Description   |
| ------------------------ | -------- | ------------- |
| `name`                   | `string` | 프로젝트 이름 |
| `description` (optional) | `string` | 프로젝트 설명 |

### Response

| Property  | Type      | Description                                        |
| --------- | --------- | -------------------------------------------------- |
| `project` | `Project` | 새로 생성된 프로젝트 (기본 그룹, 노트 데이터 포함) |

# deleteProjects

## Request

### Endpoint

`DELETE` `/project/[project.id]`

### Params

| Property     | Type     | Description        |
| ------------ | -------- | ------------------ |
| `project.id` | `number` | 프로젝트 고유 번호 |

### Response

| Property  | Type      | Description                  |
| --------- | --------- | ---------------------------- |
| `success` | `boolean` | 프로젝트 삭제 성공 또는 실패 |

# updateProjects

## Request

### Endpoint

`PUT` `/project/[project.id]`

### Params

| Property     | Type     | Description        |
| ------------ | -------- | ------------------ |
| `project.id` | `number` | 프로젝트 고유 번호 |

### Body

| Property                 | Type     | Description   |
| ------------------------ | -------- | ------------- |
| `name`                   | `string` | 프로젝트 이름 |
| `description` (optional) | `string` | 프로젝트 설명 |

### Response

| Property  | Type      | Description                      |
| --------- | --------- | -------------------------------- |
| `success` | `boolean` | 프로젝트 업데이트 성공 또는 실패 |

**Comment by zoomKoding** [comment]
와우 연호님 문서화까지 진행하셨네요! 🥇 
저도 이거 참고해서 프론트엔드 구조를 잡아보도록 하겠습니다! 👍 
프로젝트 id로 프로젝트 전체 내용 가져오는 api는 내일 좀더 상의해보면 좋을 것 같습니다 😎
고생하셨습니다🙏

**Comment by younho9** [comment]
API 정리 없이 짜려니 어렵더라구요 ㅎㅎ 아직 프로젝트 관련 밖에 없는데 나머지는 더 추가 하겠습니다

**Comment by younho9** [comment]
# API

# signIn

## Request

### Endpoint

`POST` `/login`

### Body

[Untitled](https://www.notion.so/7e361a82d1384a398b3d1b2c9ead5826)

## Response

[Untitled](https://www.notion.so/c69dd251bc204c34b9ce296d08a16622)

# getProjects

## Request

### Endpoint

`GET` `/projects/:userId`

### Params

[Untitled](https://www.notion.so/d47425b714fd412ca04fde896e226cea)

## Response

[Untitled](https://www.notion.so/bcbf7aaae31944db8a3f9d647b195636)

# getUsers

## Request

### Endpoint

`GET` `/users/[project.id]`

### Params

[Untitled](https://www.notion.so/1d74d708c72642c283fa25d8162764d3)

## Response

[Untitled](https://www.notion.so/267f2cf3f8574636bb4741840aa45261)

# getProject

## Request

### Endpoint

`GET` `/project/:id`

### Params

[Untitled](https://www.notion.so/c6adcda2a18444dfa2bf91c0cc80a2bc)

## Response

[Untitled](https://www.notion.so/3264ce9d111a4a348b744b3eacad5a63)

## Example Response

```json
{
  id: 1,
  title: 'name',
	description: 'description'
  groups: [
    {
      id: 1,
      title: '📗todo',  
      notes: [
        {
          id: 1,
          title: 'hello',
          description: 'goood',
          // writer: 'Jinhyeok',
        },
        {
          id: 2,
          title: 'hello',
          description: 'goood',
          // writer: 'Jinhyeok',
        }
      ],
    },
    {
      id: 2,
      title: '📒doing',  
      notes: [],
    },
    {
      id: 3,
      title: '📕done',  
      notes: [],
    }
  ]
};
```

# createProject

## Request

### Endpoint

`POST` `/project`

### Body

[Untitled](https://www.notion.so/08b3f0cc04bd4892b09e3e5b17aa3121)

## Response

[Untitled](https://www.notion.so/04a74ec8ec26456c835982cc16be3c69)

## Example Response

```json
{
  id: 1,
  title: 'name',
	description: 'description'
  groups: [
    {
      id: 1,
      title: '📗todo',  
      notes: [
        {
          id: 1,
          title: 'Welcome to our ToDo app',
          description: 'goood',
        }
      ],
    },
    {
      id: 2,
      title: '📒doing',  
      notes: [],
    },
    {
      id: 3,
      title: '📕done',  
      notes: [],
    }
  ]
	};
```

# deleteProject

## Request

### Endpoint

`DELETE` `/projects/id`

### Params

[Untitled](https://www.notion.so/aa4834e24125458eb2b7ae7ba28a4775)

## Response

status code

# updateProject

## Request

### Endpoint

`PUT` `/project`

### Body

[Untitled](https://www.notion.so/7a0c5f80989143c3875afb0eae42d6a4)

## Response

[Untitled](https://www.notion.so/56a0f42595874916aaa30351a6f0091a)

# createGroup

## Request

### Endpoint

`POST` `/groups`

### Body

[Untitled](https://www.notion.so/f25b97fcc5ff498ba7f4ea412be3490a)

## Response

[Untitled](https://www.notion.so/aa7920af8e3d484987bdc361b9a73def)

## Example Response

```json
{
	group: {
    id: 1,
    title: '📗todo',
  },	
	event: {
		id: 123,
		description: 'someone did something'
	},
};
```

# deleteGroup

## Request

### Endpoint

`DELETE` `/groups/id`

### Params

[Untitled](https://www.notion.so/07b448501641409391e4622defc632a0)

## Response

[Untitled](https://www.notion.so/a5f205c7ecb24021a52fde25e6a45cd7)

```json
{
	event: {
		id: 123,
		description: 'someone did something'
	},
};
```

# updateGroup

## Request

### Endpoint

`PUT` `/groups`

### Body

[Untitled](https://www.notion.so/914a80932c284dcca87c2cc5ce39780b)

## Response

[Untitled](https://www.notion.so/4dbc17651b1b4626a2e9cb00836be198)

```json
{
	event: {
		id: 123,
		description: 'someone did something'
	},
};
```

# moveGroup

### Endpoint

`PUT` `/groups/move`

### Body

[Untitled](https://www.notion.so/cab6cbba04654219ac9185f63e2dc8bb)

## Response

[Untitled](https://www.notion.so/a822d6548bae476ba28df275ad1caf59)

```json
{
	event: {
		id: 123,
		description: 'someone did something'
	},
};
```

# createNote

## Request

### Endpoint

`POST` `/notes`

### Body

[Untitled](https://www.notion.so/32aeef2884d345018c2ce267d6686878)

## Response

[Untitled](https://www.notion.so/04e33639215845b58d0ac26677bad062)

```json
{
	note: {
    id: 1,
    title: '할 일',
		descriptionL
  },	
	event: {
		id: 123,
		description: 'someone did something'
	},
};
```

# deleteNote

## Request

### Endpoint

`DELETE` `/notes/:id`

### Params

[Untitled](https://www.notion.so/cad83c3d411d40f3be58352291aafc89)

## Response

[Untitled](https://www.notion.so/2f57cecff0ba498c8587fd13173dc5cf)

```json
{
	event: {
		id: 123,
		description: 'someone did something'
	},
};
```

# updateNote

## Request

### Endpoint

`PUT` `/notes`

### Body

[Untitled](https://www.notion.so/0193b522e09d4922a81353643bb3443a)

## Response

[Untitled](https://www.notion.so/319854dccd264fb4bbb18547a3935ebc)

```json
{
	event: {
		id: 123,
		description: 'someone did something'
	},
};
```

# moveNote

## Request

### Endpoint

`PUT` `/notes/move`

### Body

[Untitled](https://www.notion.so/c1926aa8a0a942a3a0b77e76a964354d)

## Response

[Untitled](https://www.notion.so/ff008efdf2264830b3cd57e227d4a3d2)

```json
{
	event: {
		id: 123,
		description: 'someone did something'
	},
};
```
