### ISSUE TITLE
드래그앤드롭  버그

### ISSUE THREAD

**Issue by zoomKoding** [woowa-techcamp-2020/todo-7#33]
## 이슈 요약

> 해당 이슈가 어떤 이슈인지에 대한 간략한 설명을 추가합니다.

드래그앤드롭에서 발생하는 버그를 해결합니다.

## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [ ] 문자열 선택된 상태에서 마우스 다운 후 드래그 시 버그 해결
- [ ] 카드와 컬럼 두개 등록시 동시 드래그 되는 버그 해결
- [ ] 카드 추가시 노트 textarea 클릭이 안되는 버그 해결

## 참고자료

> 해당 이슈를 해결하기 위해 참고해야할 자료가 있다면 추가합니다.

🔗 [이벤트 버블링과 캡처링 ](https://ko.javascript.info/bubbling-and-capturing)

**Comment by younho9** [comment]
drag and drop에서 다른 버그가 있어서 추가했습니다..!
