### ISSUE TITLE
데이터베이스 설계하기

### ISSUE THREAD

**Issue by zoomKoding** [woowa-techcamp-2020/todo-7#8]
## 이슈 요약

> 해당 이슈가 어떤 이슈인지에 대한 간략한 설명을 추가합니다.

이번 프로젝트에 필요한 데이터 요청을 처리해줄 데이터베이스를 설계합니다.

## 체크리스트

> 이슈에 관련된 요구사항이나 확인해야할 사항이 있으면 추가합니다.

- [x] 필요한 테이블의 형태를 정의하기
- [x] 모든 요청을 처리할 수 있는지 확인하기

**Comment by zoomKoding** [comment]
## 데이터 베이스

### Users

- id(Pk)
- username
- password
- nickname
- icon(optional)
- isActive
- createdAt
- updatedAt

### UserProjectRelations

- userId
- projectId
- authority [write, read]

### Projects

- id(Pk)
- name
- description
- isActive
- createdAt
- updatedAt

### Columns

- id(Pk)
- projectId
- name
- order(optional)
- isActive
- createdAt
- updatedAt

### Notes

- id(Pk)
- columnId
- title
- description(optional)
- order
- isActive
- createdAt
- updatedAt

### Events

- id(Pk)
- projectId
- description // '@zoomKoding' moved the column 'In progress'.
- createdAt
- updatedAt

**// 구버전**

### Events

- id(Pk)
- projectId
- userId
- noteId
- columnId
- typeId
- createdAt
- updatedAt

### EventTypes

- id(Pk)
- name

**Comment by younho9** [comment]
조금 추가해야될 내용이 있는 것 같아서 재오픈 합니다..!

**Comment by younho9** [comment]
## 데이터 베이스

### Users

<img width="994" alt="스크린샷 2020-07-19 오후 9 17 44" src="https://user-images.githubusercontent.com/48426991/87874496-4afd8f80-ca05-11ea-950f-d00fd3bda43c.png">

### UserProjectRelations

<img width="994" alt="스크린샷 2020-07-19 오후 9 18 17" src="https://user-images.githubusercontent.com/48426991/87874510-5ea8f600-ca05-11ea-83d3-f32b0fd132b4.png">

### Projects

<img width="994" alt="스크린샷 2020-07-19 오후 9 18 40" src="https://user-images.githubusercontent.com/48426991/87874519-6d8fa880-ca05-11ea-8738-700f60ea179d.png">

### Groups (Columns에서 변경)

<img width="994" alt="스크린샷 2020-07-19 오후 9 19 07" src="https://user-images.githubusercontent.com/48426991/87874528-7c765b00-ca05-11ea-8bd9-a2e0479f0030.png">

### Notes

<img width="994" alt="스크린샷 2020-07-19 오후 9 20 12" src="https://user-images.githubusercontent.com/48426991/87874541-a3cd2800-ca05-11ea-969b-d7268439059d.png">

### Events

<img width="994" alt="스크린샷 2020-07-19 오후 9 20 45" src="https://user-images.githubusercontent.com/48426991/87874546-b6dff800-ca05-11ea-8bf2-3bae0f28d507.png">
